### ISSUE TITLE
Alarm Clock software is not working.

### ISSUE THREAD

**Issue by joesdu** [AospExtended/platform_packages_apps_DeskClock#4]
Clock software in the alarm clock after the time does not ring, causing the problem is very serious, to work late several times.

**Comment by ishubhamsingh** [comment]
you are using oreo alpha builds?

**Comment by joesdu** [comment]
The first time I used the 4.6 version, the alarm clock does not work, and later replaced Oreo, because not working too many functions, so the brush back to 4.6. This alarm clock works, but the Open Gapps brush Google package, in the settings interface is always wrong.
